import XCTest
@testable import RommpleTVKit

// MARK: - Synthetic firmware
//
// Nothing in this file is a BIOS image. No test writes, reads or expects a
// 524,288-byte blob: the payloads here are a few hundred generated bytes and
// every checksum is computed from those bytes by `IncrementalFileDigest` — the
// same type the manager verifies with, which `FileIntegrityTests` already pins
// against published vectors.
//
// The real catalogue's three MD5s cannot be produced without the real images, so
// tests that need a *valid installed BIOS* run against `SyntheticBIOS.catalog`:
// the production file names, the production exclusion list and the production
// region rules, with a small byte count and computed digests substituted for the
// two values that would otherwise require shipping firmware.
// `testShippedCatalogCarriesTheThreeStandardNamesSizeAndChecksums` pins the real
// values, and every selection rule is *also* exercised against the real
// catalogue by the live-shaped-list tests below, which never reach a transfer.

private func md5Hex(_ data: Data) -> String {
    var digest = IncrementalFileDigest()
    digest.update(data)
    return digest.finalized().md5
}

private func sha1Hex(_ data: Data) -> String {
    var digest = IncrementalFileDigest()
    digest.update(data)
    return digest.finalized().sha1
}

private func crc32Hex(_ data: Data) -> String {
    var digest = IncrementalFileDigest()
    digest.update(data)
    return digest.finalized().crc32
}

private enum SyntheticBIOS {
    /// Deliberately not 524,288. A test fixture that is the size of a BIOS is a
    /// test fixture someone will one day mistake for one.
    static let byteCount: Int64 = 512

    static func payload(seed: UInt8) -> Data {
        Data((0..<Int(byteCount)).map { UInt8(truncatingIfNeeded: $0 &* 7) &+ seed })
    }

    static let japan = payload(seed: 0x11)
    static let usa = payload(seed: 0x22)
    static let europe = payload(seed: 0x33)

    static let catalog = PS1BIOSCatalog(
        byteCount: byteCount,
        japan: .init(fileName: "scph5500.bin", md5: md5Hex(japan)),
        usa: .init(fileName: "scph5501.bin", md5: md5Hex(usa)),
        europe: .init(fileName: "scph5502.bin", md5: md5Hex(europe)),
        excludedFileNames: PS1BIOSCatalog.playStation.excludedFileNames)

    /// The bytes whose MD5 is the catalogue's, for the three standard names and
    /// for the aliases that share one of those checksums on the real server.
    static func payload(named fileName: String) -> Data? {
        switch fileName.lowercased() {
        case "scph5500.bin": return japan
        case "scph5501.bin", "scph7003.bin": return usa
        case "scph5502.bin", "scph5552.bin": return europe
        default: return nil
        }
    }
}

/// A stand-in for one RomM server's `/api/firmware` list plus the bytes behind
/// it. Records every list call, every content request and every transfer, so a
/// test can assert that the network was not touched at all.
private final class FakeFirmwareServer: @unchecked Sendable {

    private let lock = NSLock()
    private var rows: [RommFirmware] = []
    private var payloads: [Int: Data] = [:]
    private var idsByURL: [String: Int] = [:]

    private var listCallsStorage: [Int] = []
    private var requestedStorage: [(id: Int, fileName: String)] = []
    private var transferredStorage: [(id: Int, expected: ExpectedFileIntegrity)] = []

    /// Runs before the firmware list resolves; throw to fail it.
    var listHook: (@Sendable (Int) async throws -> Void)?
    /// Runs before a transfer writes anything; throw to fail it.
    var transferHook: (@Sendable (Int, URL) async throws -> Void)?

    // MARK: Building

    @discardableResult
    func add(_ fileName: String,
             id: Int,
             sizeBytes: Int64 = SyntheticBIOS.byteCount,
             md5: String? = nil,
             sha1: String? = nil,
             crc: String? = nil,
             verified: Bool = true,
             missingFromFS: Bool = false,
             payload: Data? = nil) -> RommFirmware {
        let bytes = payload ?? SyntheticBIOS.payload(named: fileName)
        let row = RommFirmware(id: id,
                               fileName: fileName,
                               fileSizeBytes: sizeBytes,
                               isVerified: verified,
                               crcHash: crc ?? bytes.map(crc32Hex),
                               md5Hash: md5 ?? bytes.map(md5Hex),
                               sha1Hash: sha1 ?? bytes.map(sha1Hex),
                               missingFromFS: missingFromFS,
                               updatedAt: "2026-02-03T04:05:06")
        lock.lock()
        rows.append(row)
        payloads[id] = bytes
        lock.unlock()
        return row
    }

    /// Serves bytes that are not the ones the row's checksums describe.
    func corruptPayload(id: Int) {
        lock.lock()
        payloads[id] = Data(repeating: 0xAB, count: Int(SyntheticBIOS.byteCount))
        lock.unlock()
    }

    func publish(_ replacement: [RommFirmware]) {
        lock.lock()
        rows = replacement
        lock.unlock()
    }

    // MARK: Observation

    var listCalls: [Int] { lock.lock(); defer { lock.unlock() }; return listCallsStorage }
    var requestedNames: [String] {
        lock.lock(); defer { lock.unlock() }; return requestedStorage.map(\.fileName)
    }
    var requestedIDs: [Int] {
        lock.lock(); defer { lock.unlock() }; return requestedStorage.map(\.id)
    }
    var transferredIDs: [Int] {
        lock.lock(); defer { lock.unlock() }; return transferredStorage.map(\.id)
    }
    func expectation(forID id: Int) -> ExpectedFileIntegrity? {
        lock.lock(); defer { lock.unlock() }
        return transferredStorage.first { $0.id == id }?.expected
    }

    // MARK: Seams

    private func recordListCall(_ platformID: Int) {
        lock.lock(); listCallsStorage.append(platformID); lock.unlock()
    }

    private func recordRequest(_ id: Int, _ fileName: String, _ url: URL) {
        lock.lock()
        requestedStorage.append((id, fileName))
        idsByURL[url.absoluteString] = id
        lock.unlock()
    }

    /// Records the transfer and answers the id and bytes behind the request.
    private func beginTransfer(_ request: URLRequest,
                               _ expected: ExpectedFileIntegrity) -> (id: Int, payload: Data?)? {
        lock.lock(); defer { lock.unlock() }
        guard let id = idsByURL[request.url!.absoluteString] else { return nil }
        transferredStorage.append((id, expected))
        return (id, payloads[id])
    }

    var published: [RommFirmware] { lock.lock(); defer { lock.unlock() }; return rows }

    var loadFirmware: @Sendable (Int) async throws -> [RommFirmware] {
        { [self] platformID in
            recordListCall(platformID)
            if let hook = listHook { try await hook(platformID) }
            return published
        }
    }

    var buildRequest: @Sendable (Int, String) -> URLRequest {
        { [self] id, fileName in
            let encoded = fileName
                .addingPercentEncoding(withAllowedCharacters: .urlPathAllowed)!
            let url = URL(string: "https://firmware.invalid/api/firmware/\(id)/content/\(encoded)")!
            recordRequest(id, fileName, url)
            return URLRequest(url: url)
        }
    }

    /// Mirrors `StreamingFileDownloader.download`: the bytes land at the part
    /// path, the returned digest describes those bytes, progress is cumulative,
    /// and a failed check removes the part file rather than leaving it.
    var transfer: PS1FileTransfer {
        { [self] request, partURL, expected, progress in
            guard let begun = beginTransfer(request, expected) else { throw URLError(.badURL) }
            if let hook = transferHook {
                do { try await hook(begun.id, partURL) } catch {
                    try? FileManager.default.removeItem(at: partURL)
                    throw error
                }
            }
            guard let payload = begun.payload else { throw FileIntegrityError.httpStatus(404) }
            do {
                try payload.write(to: partURL)
                // Two reports for one file, so a test can see that progress is
                // cumulative rather than a single jump to the end.
                progress(Int64(payload.count / 2))
                progress(Int64(payload.count))
                var digest = IncrementalFileDigest()
                digest.update(payload)
                let result = digest.finalized()
                try expected.verify(result)
                return result
            } catch {
                try? FileManager.default.removeItem(at: partURL)
                throw error
            }
        }
    }
}

private struct SentinelError: Error, Equatable {}

// MARK: - Tests

final class PS1FirmwareManagerTests: XCTestCase {

    // MARK: Fixtures

    private func tempDirectory() throws -> URL {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        addTeardownBlock { try? FileManager.default.removeItem(at: url) }
        return url
    }

    private func makeManager(cacheRoot: URL,
                             server: FakeFirmwareServer,
                             catalog: PS1BIOSCatalog = SyntheticBIOS.catalog)
    throws -> PS1FirmwareManager {
        try PS1FirmwareManager(cacheRoot: cacheRoot,
                               catalog: catalog,
                               loadFirmware: server.loadFirmware,
                               buildRequest: server.buildRequest,
                               transfer: server.transfer)
    }

    /// A firmware list shaped like the one the target server publishes: the three
    /// standard images, two aliases that duplicate a required checksum under
    /// another name, the three images this phase excludes (including the
    /// uppercase spelling the server uses), an unverified row and a row whose
    /// file is missing from storage.
    private func liveShapedServer(_ catalog: PS1BIOSCatalog) -> FakeFirmwareServer {
        let server = FakeFirmwareServer()
        let size = catalog.byteCount
        server.add("scph5500.bin", id: 101, sizeBytes: size, md5: catalog.japan.md5)
        server.add("scph5501.bin", id: 102, sizeBytes: size, md5: catalog.usa.md5)
        server.add("scph5502.bin", id: 103, sizeBytes: size, md5: catalog.europe.md5)
        // Aliases: same bytes, same MD5, different name.
        server.add("scph5552.bin", id: 104, sizeBytes: size, md5: catalog.europe.md5)
        server.add("scph7003.bin", id: 105, sizeBytes: size, md5: catalog.usa.md5)
        // Excluded by this phase; all present, all verified, all the right size.
        server.add("openbios.bin", id: 106, sizeBytes: size)
        server.add("ps1_rom.bin", id: 107, sizeBytes: size)
        server.add("PSXONPSP660.BIN", id: 108, sizeBytes: size)
        server.add("scph1001.bin", id: 109, sizeBytes: size, verified: false)
        server.add("scph7502.bin", id: 110, sizeBytes: size, missingFromFS: true)
        return server
    }

    private func rom(regions: [String], platformID: Int = 4231) -> Rom {
        Rom(id: 77, name: "Signal Drift", fsName: "Signal Drift.cue", platformId: platformID,
            sizeBytes: nil, coverPath: nil, regions: regions)
    }

    private func names(in directory: URL) -> [String] {
        ((try? FileManager.default.contentsOfDirectory(atPath: directory.path)) ?? []).sorted()
    }

    private func bytes(_ url: URL) -> Data? { try? Data(contentsOf: url) }

    /// A file URL under `root` whose absolute path is exactly `length` bytes,
    /// with any intermediate directories created.
    private func path(ofExactLength length: Int, under root: URL) throws -> URL {
        var url = root
        while true {
            let remaining = length - url.path.utf8.count - 1
            XCTAssertGreaterThan(remaining, 0, "no room for a \(length)-byte path")
            if remaining <= 255 {
                return url.appendingPathComponent(String(repeating: "z", count: remaining),
                                                  isDirectory: false)
            }
            url.appendPathComponent(String(repeating: "d", count: 255), isDirectory: true)
            try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        }
    }

    private func modificationDate(_ url: URL) -> Date? {
        (try? FileManager.default.attributesOfItem(atPath: url.path))?[.modificationDate] as? Date
    }

    /// Installs `entry`'s synthetic payload the way a previous successful run
    /// would have left it.
    @discardableResult
    private func installValid(_ entry: PS1BIOSCatalog.Entry, in systemDirectory: URL) throws -> URL {
        let url = systemDirectory.appendingPathComponent(entry.fileName, isDirectory: false)
        try XCTUnwrap(SyntheticBIOS.payload(named: entry.fileName)).write(to: url)
        return url
    }

    // MARK: - Region mapping

    func testUSARegionRequiresTheAmericanBIOS() {
        XCTAssertEqual(PS1BIOSRegion.required(for: ["USA"]), [.usa])
        XCTAssertEqual(SyntheticBIOS.catalog[.usa].fileName, "scph5501.bin")
        XCTAssertEqual(PS1BIOSCatalog.playStation[.usa].fileName, "scph5501.bin")
    }

    func testJapanRegionRequiresTheJapaneseBIOS() {
        XCTAssertEqual(PS1BIOSRegion.required(for: ["Japan"]), [.japan])
        XCTAssertEqual(PS1BIOSCatalog.playStation[.japan].fileName, "scph5500.bin")
    }

    func testEuropeAndPALRegionsRequireTheEuropeanBIOS() {
        for tag in ["Europe", "PAL", "E", "eur", "UK", "Australia"] {
            XCTAssertEqual(PS1BIOSRegion.required(for: [tag]), [.europe], "tag \(tag)")
        }
        XCTAssertEqual(PS1BIOSCatalog.playStation[.europe].fileName, "scph5502.bin")
    }

    func testUnknownRegionRequiresAllThreeStandardBIOSFiles() {
        let all: [PS1BIOSRegion] = [.japan, .usa, .europe]
        XCTAssertEqual(PS1BIOSRegion.required(for: []), all)
        XCTAssertEqual(PS1BIOSRegion.required(for: ["World"]), all)
        XCTAssertEqual(PS1BIOSRegion.required(for: ["Unknown"]), all)
        XCTAssertEqual(PS1BIOSRegion.required(for: [""]), all)
        // One unrecognized tag alongside a recognized one is still unknown: the
        // safe answer is every BIOS, not the half of the answer we understood.
        XCTAssertEqual(PS1BIOSRegion.required(for: ["USA", "Mars"]), all)
    }

    func testMixedRegionsRequireAllThreeStandardBIOSFiles() {
        XCTAssertEqual(PS1BIOSRegion.required(for: ["USA", "Europe"]),
                       [.japan, .usa, .europe])
        XCTAssertEqual(PS1BIOSRegion.required(for: ["Japan", "USA", "Europe"]),
                       [.japan, .usa, .europe])
    }

    func testRegionTagsAreMatchedIgnoringCaseAndSeparators() {
        XCTAssertEqual(PS1BIOSRegion.required(for: ["usa"]), [.usa])
        XCTAssertEqual(PS1BIOSRegion.required(for: [" USA "]), [.usa])
        XCTAssertEqual(PS1BIOSRegion.required(for: ["North_America"]), [.usa])
        XCTAssertEqual(PS1BIOSRegion.required(for: ["north america"]), [.usa])
        XCTAssertEqual(PS1BIOSRegion.required(for: ["NTSC-U"]), [.usa])
        XCTAssertEqual(PS1BIOSRegion.required(for: ["NTSC-J"]), [.japan])
    }

    func testSynonymsForOneRegionStillRequireOneBIOS() {
        XCTAssertEqual(PS1BIOSRegion.required(for: ["USA", "U", "us"]), [.usa])
    }

    // MARK: - The shipped catalogue

    func testShippedCatalogCarriesTheThreeStandardNamesSizeAndChecksums() {
        let catalog = PS1BIOSCatalog.playStation
        XCTAssertEqual(catalog.byteCount, 524_288)
        XCTAssertEqual(catalog.japan,
                       .init(fileName: "scph5500.bin", md5: "8dd7d5296a650fac7319bce665a6a53c"))
        XCTAssertEqual(catalog.usa,
                       .init(fileName: "scph5501.bin", md5: "490f666e1afb15b7362b406ed1cea246"))
        XCTAssertEqual(catalog.europe,
                       .init(fileName: "scph5502.bin", md5: "32736f17079d0b2b7024407c39bd3050"))
    }

    func testExcludedNamesAreNeverRecognizedNames() {
        let catalog = PS1BIOSCatalog.playStation
        XCTAssertEqual(catalog.excludedFileNames,
                       ["openbios.bin", "ps1_rom.bin", "psxonpsp660.bin"])
        // The rule that does the work is the allow-list; this is the tripwire that
        // fires if one of these names is ever added to it.
        let recognized = Set(catalog.allEntries.map(\.fileName))
        XCTAssertTrue(catalog.excludedFileNames.isDisjoint(with: recognized))
        for name in ["openbios.bin", "ps1_rom.bin", "PSXONPSP660.BIN", "PS1_ROM.BIN"] {
            XCTAssertNil(catalog.entry(matching: name), name)
        }
    }

    func testCatalogMatchesRecognizedNamesIgnoringCase() {
        let catalog = PS1BIOSCatalog.playStation
        XCTAssertEqual(catalog.entry(matching: "SCPH5501.BIN"), catalog.usa)
        XCTAssertEqual(catalog.entry(matching: "scph5501.bin"), catalog.usa)
        XCTAssertNil(catalog.entry(matching: "scph5552.bin"))
        XCTAssertNil(catalog.entry(matching: "scph7003.bin"))
        XCTAssertNil(catalog.entry(matching: "psx/scph5501.bin"))
    }

    // MARK: - Selection against the real catalogue
    //
    // These run with `PS1BIOSCatalog.playStation`, so the 524,288-byte rule and
    // the real MD5 constants are the ones under test. None of them reaches a
    // successful transfer, which is what lets them assert the production
    // constants without a firmware image.

    func testLiveShapedListSelectsOnlyTheAmericanEntryForAUSAGame() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let server = liveShapedServer(catalog)
        server.transferHook = { _, _ in throw SentinelError() }
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server,
                                      catalog: catalog)

        do {
            _ = try await manager.prepare(for: rom(regions: ["USA"]))
            XCTFail("expected the sentinel transfer failure")
        } catch is SentinelError {
            // The transfer was reached, which is the point: selection resolved.
        }
        XCTAssertEqual(server.requestedNames, ["scph5501.bin"])
        XCTAssertEqual(server.requestedIDs, [102])
        XCTAssertEqual(server.expectation(forID: 102)?.md5, catalog.usa.md5)
        XCTAssertEqual(server.expectation(forID: 102)?.size, 524_288)
    }

    func testSelectionOverALiveShapedListPicksEachStandardEntryByName() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let rows = liveShapedServer(catalog).published
        let manager = try makeManager(cacheRoot: try tempDirectory(),
                                      server: FakeFirmwareServer(), catalog: catalog)

        // Aliases (104, 105), excluded images (106-108), the unverified row (109)
        // and the row whose file is gone (110) are all in `rows`, all 524,288
        // bytes, and none of them is what any of these three resolve to.
        let japan = try await manager.select(catalog.japan, from: rows)
        let usa = try await manager.select(catalog.usa, from: rows)
        let europe = try await manager.select(catalog.europe, from: rows)
        XCTAssertEqual(japan.id, 101)
        XCTAssertEqual(usa.id, 102)
        XCTAssertEqual(europe.id, 103)
    }

    func testSelectionPrefersTheExactSpellingAndThenTheLowestID() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let server = FakeFirmwareServer()
        server.add("SCPH5501.BIN", id: 12, sizeBytes: 524_288, md5: catalog.usa.md5)
        server.add("scph5501.bin", id: 34, sizeBytes: 524_288, md5: catalog.usa.md5)
        server.add("scph5501.bin", id: 56, sizeBytes: 524_288, md5: catalog.usa.md5)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server,
                                      catalog: catalog)

        let chosen = try await manager.select(catalog.usa, from: server.published)
        XCTAssertEqual(chosen.id, 34)
    }

    func testSelectionSkipsAnUnusableDuplicateForAUsableOne() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let server = FakeFirmwareServer()
        server.add("scph5501.bin", id: 12, sizeBytes: 524_288, md5: catalog.usa.md5,
                   verified: false)
        server.add("scph5501.bin", id: 34, sizeBytes: 524_288, md5: catalog.usa.md5)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server,
                                      catalog: catalog)

        let chosen = try await manager.select(catalog.usa, from: server.published)
        XCTAssertEqual(chosen.id, 34)
    }

    func testExcludedFirmwareIsNeverRequestedEvenWhenItIsTheOnlyThingOnTheServer() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let server = FakeFirmwareServer()
        server.add("openbios.bin", id: 206, sizeBytes: 524_288)
        server.add("ps1_rom.bin", id: 207, sizeBytes: 524_288)
        server.add("PSXONPSP660.BIN", id: 208, sizeBytes: 524_288)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server,
                                      catalog: catalog)

        do {
            _ = try await manager.prepare(for: rom(regions: ["USA"]))
            XCTFail("expected a missing-firmware failure")
        } catch let error as PS1FirmwareError {
            XCTAssertEqual(error, .firmwareNotOnServer(fileName: "scph5501.bin"))
        }
        XCTAssertEqual(server.requestedNames, [])
        XCTAssertEqual(server.transferredIDs, [])
    }

    func testAnAliasSharingARequiredChecksumIsNotSelectedInItsPlace() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let server = FakeFirmwareServer()
        // `scph5552.bin` carries `scph5502.bin`'s MD5 on the real server. A
        // digest-keyed selector would take it; a name-keyed one cannot.
        server.add("scph5552.bin", id: 304, sizeBytes: 524_288, md5: catalog.europe.md5)
        server.add("scph7003.bin", id: 305, sizeBytes: 524_288, md5: catalog.usa.md5)
        let cacheRoot = try tempDirectory()
        let manager = try makeManager(cacheRoot: cacheRoot, server: server, catalog: catalog)

        do {
            _ = try await manager.prepare(for: rom(regions: ["Europe"]))
            XCTFail("expected a missing-firmware failure")
        } catch let error as PS1FirmwareError {
            XCTAssertEqual(error, .firmwareNotOnServer(fileName: "scph5502.bin"))
        }
        XCTAssertEqual(server.requestedNames, [])
        XCTAssertEqual(server.transferredIDs, [])
        XCTAssertEqual(names(in: manager.systemDirectory), [])
    }

    func testFirmwareThatIsMissingFromServerStorageIsRejected() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let server = FakeFirmwareServer()
        server.add("scph5501.bin", id: 402, sizeBytes: 524_288, md5: catalog.usa.md5,
                   missingFromFS: true)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server,
                                      catalog: catalog)

        await assertPrepareFails(manager, regions: ["USA"],
                                 with: .firmwareUnusable(fileName: "scph5501.bin",
                                                         rejection: .missingFromStorage))
        XCTAssertEqual(server.transferredIDs, [])
    }

    func testUnverifiedFirmwareIsRejected() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let server = FakeFirmwareServer()
        server.add("scph5501.bin", id: 402, sizeBytes: 524_288, md5: catalog.usa.md5,
                   verified: false)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server,
                                      catalog: catalog)

        await assertPrepareFails(manager, regions: ["USA"],
                                 with: .firmwareUnusable(fileName: "scph5501.bin",
                                                         rejection: .unverified))
        XCTAssertEqual(server.transferredIDs, [])
    }

    func testWrongSizedFirmwareIsRejected() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let server = FakeFirmwareServer()
        server.add("scph5501.bin", id: 402, sizeBytes: 262_144, md5: catalog.usa.md5)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server,
                                      catalog: catalog)

        await assertPrepareFails(manager, regions: ["USA"],
                                 with: .firmwareUnusable(
                                    fileName: "scph5501.bin",
                                    rejection: .wrongSize(byteCount: 262_144,
                                                          expected: 524_288)))
        XCTAssertEqual(server.transferredIDs, [])
    }

    func testFirmwareWhoseDeclaredChecksumIsNotTheStandardOneIsRejected() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let server = FakeFirmwareServer()
        // The European image's MD5 published under the American name.
        server.add("scph5501.bin", id: 402, sizeBytes: 524_288, md5: catalog.europe.md5)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server,
                                      catalog: catalog)

        await assertPrepareFails(manager, regions: ["USA"],
                                 with: .firmwareUnusable(
                                    fileName: "scph5501.bin",
                                    rejection: .declaredChecksumMismatch(
                                        declared: catalog.europe.md5)))
        XCTAssertEqual(server.transferredIDs, [])
    }

    func testAServerChecksumInAnyCaseIsAccepted() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let server = FakeFirmwareServer()
        server.add("scph5501.bin", id: 402, sizeBytes: 524_288,
                   md5: catalog.usa.md5.uppercased())
        server.transferHook = { _, _ in throw SentinelError() }
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server,
                                      catalog: catalog)

        do {
            _ = try await manager.prepare(for: rom(regions: ["USA"]))
            XCTFail("expected the sentinel transfer failure")
        } catch is SentinelError {}
        XCTAssertEqual(server.requestedIDs, [402])
    }

    func testFirmwareWithAnUnrecognizedNameIsNeverSelected() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let server = FakeFirmwareServer()
        server.add("scph1001.bin", id: 501, sizeBytes: 524_288)
        server.add("bios.bin", id: 502, sizeBytes: 524_288)
        server.add("SCPH5501.BIN.bak", id: 503, sizeBytes: 524_288)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server,
                                      catalog: catalog)

        await assertPrepareFails(manager, regions: ["USA"],
                                 with: .firmwareNotOnServer(fileName: "scph5501.bin"))
        XCTAssertEqual(server.requestedNames, [])
    }

    func testTheChecksumHandedToTheTransferIsTheStandardOneEvenWhenTheServerHasNone() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let server = FakeFirmwareServer()
        // A row with no checksums at all, which RomM's schema permits.
        server.publish([RommFirmware(id: 402, fileName: "scph5501.bin",
                                     fileSizeBytes: 524_288, isVerified: true,
                                     crcHash: nil, md5Hash: nil, sha1Hash: nil,
                                     missingFromFS: false,
                                     updatedAt: "2026-02-03T04:05:06")])
        server.transferHook = { _, _ in throw SentinelError() }
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server,
                                      catalog: catalog)

        do {
            _ = try await manager.prepare(for: rom(regions: ["USA"]))
            XCTFail("expected the sentinel transfer failure")
        } catch is SentinelError {}
        let expected = try XCTUnwrap(server.expectation(forID: 402))
        XCTAssertEqual(expected.md5, catalog.usa.md5)
        XCTAssertEqual(expected.size, 524_288)
        XCTAssertNil(expected.sha1)
        XCTAssertNil(expected.crc32)
    }

    func testServerSuppliedChecksumsAreAlsoHandedToTheTransfer() async throws {
        let catalog = PS1BIOSCatalog.playStation
        let server = FakeFirmwareServer()
        let sha1 = String(repeating: "a", count: 40)
        let crc = "0badf00d"
        server.publish([RommFirmware(id: 402, fileName: "scph5501.bin",
                                     fileSizeBytes: 524_288, isVerified: true,
                                     crcHash: crc, md5Hash: catalog.usa.md5,
                                     sha1Hash: sha1, missingFromFS: false,
                                     updatedAt: "2026-02-03T04:05:06")])
        server.transferHook = { _, _ in throw SentinelError() }
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server,
                                      catalog: catalog)

        do {
            _ = try await manager.prepare(for: rom(regions: ["USA"]))
            XCTFail("expected the sentinel transfer failure")
        } catch is SentinelError {}
        let expected = try XCTUnwrap(server.expectation(forID: 402))
        XCTAssertEqual(expected.md5, catalog.usa.md5)
        XCTAssertEqual(expected.sha1, sha1)
        XCTAssertEqual(expected.crc32, crc)
    }

    // MARK: - Installing

    func testUSAGameInstallsOnlyTheAmericanBIOS() async throws {
        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server)

        let systemDirectory = try await manager.prepare(for: rom(regions: ["USA"]))

        XCTAssertEqual(names(in: systemDirectory), ["scph5501.bin"])
        XCTAssertEqual(bytes(systemDirectory.appendingPathComponent("scph5501.bin")),
                       SyntheticBIOS.usa)
        XCTAssertEqual(server.requestedIDs, [102])
    }

    func testJapaneseGameInstallsOnlyTheJapaneseBIOS() async throws {
        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server)

        let systemDirectory = try await manager.prepare(for: rom(regions: ["Japan"]))

        XCTAssertEqual(names(in: systemDirectory), ["scph5500.bin"])
        XCTAssertEqual(bytes(systemDirectory.appendingPathComponent("scph5500.bin")),
                       SyntheticBIOS.japan)
    }

    func testEuropeanGameInstallsOnlyTheEuropeanBIOS() async throws {
        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server)

        let systemDirectory = try await manager.prepare(for: rom(regions: ["PAL"]))

        XCTAssertEqual(names(in: systemDirectory), ["scph5502.bin"])
        XCTAssertEqual(bytes(systemDirectory.appendingPathComponent("scph5502.bin")),
                       SyntheticBIOS.europe)
    }

    func testUnknownRegionInstallsAllThreeStandardBIOSFilesAndNothingElse() async throws {
        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server)

        let systemDirectory = try await manager.prepare(for: rom(regions: ["World"]))

        XCTAssertEqual(names(in: systemDirectory),
                       ["scph5500.bin", "scph5501.bin", "scph5502.bin"])
        XCTAssertEqual(server.requestedIDs, [101, 102, 103])
    }

    func testARemoteNameInAnotherCaseInstallsUnderTheCoreRecognizedSpelling() async throws {
        let server = FakeFirmwareServer()
        server.add("SCPH5501.BIN", id: 602, payload: SyntheticBIOS.usa)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server)

        let systemDirectory = try await manager.prepare(for: rom(regions: ["USA"]))

        // `contentsOfDirectory` reports the name as it was created, which is what
        // makes this meaningful on a case-insensitive volume.
        XCTAssertEqual(names(in: systemDirectory), ["scph5501.bin"])
        // The request keeps the server's spelling: that is the path on the server.
        XCTAssertEqual(server.requestedNames, ["SCPH5501.BIN"])
    }

    func testPreparationUsesThePlatformIDTheCallerDiscovered() async throws {
        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: try tempDirectory(), server: server)

        _ = try await manager.prepare(for: rom(regions: ["USA"], platformID: 4231))

        XCTAssertEqual(server.listCalls, [4231])
    }

    func testTheSystemDirectoryIsCachesPS1System() async throws {
        let cacheRoot = try tempDirectory()
        let manager = try makeManager(cacheRoot: cacheRoot, server: FakeFirmwareServer())

        let directory = manager.systemDirectory
        XCTAssertEqual(directory.lastPathComponent, "system")
        XCTAssertEqual(directory.deletingLastPathComponent().lastPathComponent, "ps1")
        XCTAssertEqual(directory.deletingLastPathComponent().deletingLastPathComponent().path,
                       cacheRoot.path)
        var isDirectory: ObjCBool = false
        XCTAssertTrue(FileManager.default.fileExists(atPath: directory.path,
                                                     isDirectory: &isDirectory))
        XCTAssertTrue(isDirectory.boolValue)
    }

    func testAClientBackedManagerOwnsTheSameSystemDirectory() async throws {
        let cacheRoot = try tempDirectory()
        let client = RommClient(config: RommConfig(baseURL: URL(string: "https://library.invalid")!,
                                                   token: "not-a-real-token"))
        let manager = try PS1FirmwareManager(client: client, cacheRoot: cacheRoot)

        let directory = manager.systemDirectory
        XCTAssertEqual(directory.path,
                       cacheRoot.appendingPathComponent("ps1", isDirectory: true)
                           .appendingPathComponent("system", isDirectory: true).path)
    }

    // MARK: - The cache

    func testAValidCachedBIOSMakesNoNetworkRequestAtAll() async throws {
        let cacheRoot = try tempDirectory()
        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: cacheRoot, server: server)
        let systemDirectory = try await manager.prepare(for: rom(regions: ["USA"]))
        let installed = systemDirectory.appendingPathComponent("scph5501.bin")
        let stamp = try XCTUnwrap(modificationDate(installed))

        // A second manager over the same cache root, so nothing is remembered in
        // memory: the answer has to come from the bytes on disk.
        let second = FakeFirmwareServer()
        let secondManager = try makeManager(cacheRoot: cacheRoot, server: second)
        let again = try await secondManager.prepare(for: rom(regions: ["USA"]))

        XCTAssertEqual(again.path, systemDirectory.path)
        XCTAssertEqual(second.listCalls, [])
        XCTAssertEqual(second.requestedNames, [])
        XCTAssertEqual(second.transferredIDs, [])
        XCTAssertEqual(bytes(installed), SyntheticBIOS.usa)
        XCTAssertEqual(modificationDate(installed), stamp)
    }

    func testOnlyTheMissingBIOSFilesAreFetched() async throws {
        let cacheRoot = try tempDirectory()
        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: cacheRoot, server: server)
        let systemDirectory = manager.systemDirectory
        let installed = try installValid(SyntheticBIOS.catalog[.usa], in: systemDirectory)
        let stamp = try XCTUnwrap(modificationDate(installed))

        _ = try await manager.prepare(for: rom(regions: ["World"]))

        XCTAssertEqual(server.requestedNames, ["scph5500.bin", "scph5502.bin"])
        XCTAssertEqual(bytes(installed), SyntheticBIOS.usa)
        XCTAssertEqual(modificationDate(installed), stamp)
    }

    func testACorruptCachedBIOSIsFetchedAgainAndReplaced() async throws {
        let cacheRoot = try tempDirectory()
        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: cacheRoot, server: server)
        let systemDirectory = manager.systemDirectory
        let path = systemDirectory.appendingPathComponent("scph5501.bin")
        // Right size, wrong bytes: only a checksum can tell.
        try Data(repeating: 0x5A, count: Int(SyntheticBIOS.byteCount)).write(to: path)

        _ = try await manager.prepare(for: rom(regions: ["USA"]))

        XCTAssertEqual(server.requestedIDs, [102])
        XCTAssertEqual(bytes(path), SyntheticBIOS.usa)
    }

    func testAWrongSizedCachedBIOSIsFetchedAgain() async throws {
        let cacheRoot = try tempDirectory()
        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: cacheRoot, server: server)
        let systemDirectory = manager.systemDirectory
        let path = systemDirectory.appendingPathComponent("scph5501.bin")
        try Data(SyntheticBIOS.usa.prefix(16)).write(to: path)

        _ = try await manager.prepare(for: rom(regions: ["USA"]))

        XCTAssertEqual(server.requestedIDs, [102])
        XCTAssertEqual(bytes(path), SyntheticBIOS.usa)
    }

    func testASymbolicLinkAtABIOSPathIsReplacedRatherThanWrittenThrough() async throws {
        let cacheRoot = try tempDirectory()
        let elsewhere = try tempDirectory()
        let target = elsewhere.appendingPathComponent("someone-elses-file.bin")
        // The link's target is a *valid* image, so the size and checksum checks
        // cannot be what refuses it: only "this is not a regular file" can.
        try SyntheticBIOS.usa.write(to: target)

        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: cacheRoot, server: server)
        let systemDirectory = manager.systemDirectory
        let path = systemDirectory.appendingPathComponent("scph5501.bin")
        try FileManager.default.createSymbolicLink(at: path, withDestinationURL: target)

        _ = try await manager.prepare(for: rom(regions: ["USA"]))

        XCTAssertEqual(server.requestedIDs, [102])
        XCTAssertEqual(bytes(path), SyntheticBIOS.usa)
        XCTAssertEqual((try FileManager.default.attributesOfItem(atPath: path.path))[.type]
                        as? FileAttributeType, .typeRegular)
        // Written to the link's own name, never through it.
        XCTAssertTrue(FileManager.default.fileExists(atPath: target.path))
    }

    func testASymbolicLinkIsNotABIOSHoweverGoodItsTargetIs() async throws {
        let cacheRoot = try tempDirectory()
        let elsewhere = try tempDirectory()
        // A link's own reported size is the length of the path it holds, so a
        // link to a valid image is normally rejected by the size check before
        // anything reads it. This one is planted with a target path exactly as
        // long as the image, which is the case where only "not a regular file"
        // can refuse it — and is a length an attacker who can plant a link can
        // choose freely.
        let target = try path(ofExactLength: Int(SyntheticBIOS.byteCount), under: elsewhere)
        try SyntheticBIOS.usa.write(to: target)
        XCTAssertEqual(target.path.utf8.count, Int(SyntheticBIOS.byteCount))

        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: cacheRoot, server: server)
        let path = manager.systemDirectory.appendingPathComponent("scph5501.bin")
        try FileManager.default.createSymbolicLink(at: path, withDestinationURL: target)
        // The trap is only a trap if the link looks like an installed image.
        let linkAttributes = try FileManager.default.attributesOfItem(atPath: path.path)
        XCTAssertEqual((linkAttributes[.size] as? NSNumber)?.int64Value,
                       SyntheticBIOS.byteCount)
        XCTAssertEqual(PS1FirmwareManager.digest(ofFileAt: path)?.md5,
                       SyntheticBIOS.catalog.usa.md5)

        _ = try await manager.prepare(for: rom(regions: ["USA"]))

        XCTAssertEqual(server.requestedIDs, [102])
        XCTAssertEqual((try FileManager.default.attributesOfItem(atPath: path.path))[.type]
                        as? FileAttributeType, .typeRegular)
    }

    // MARK: - A failure never costs a working BIOS

    func testAServerSideRefusalLeavesAnAlreadyValidBIOSUntouched() async throws {
        let cacheRoot = try tempDirectory()
        let server = FakeFirmwareServer()
        server.add("scph5500.bin", id: 101)
        // No European entry at all, so preparing for an unknown region fails.
        let manager = try makeManager(cacheRoot: cacheRoot, server: server)
        let systemDirectory = manager.systemDirectory
        let installed = try installValid(SyntheticBIOS.catalog[.usa], in: systemDirectory)
        let stamp = try XCTUnwrap(modificationDate(installed))

        await assertPrepareFails(manager, regions: ["World"],
                                 with: .firmwareNotOnServer(fileName: "scph5502.bin"))

        XCTAssertEqual(bytes(installed), SyntheticBIOS.usa)
        XCTAssertEqual(modificationDate(installed), stamp)
        XCTAssertTrue(names(in: systemDirectory).contains("scph5501.bin"))
    }

    func testAFailedTransferKeepsBothTheFinishedAndThePreexistingBIOS() async throws {
        let cacheRoot = try tempDirectory()
        let server = liveShapedServer(SyntheticBIOS.catalog)
        // The European image fails after the Japanese one has been installed.
        server.transferHook = { id, _ in if id == 103 { throw SentinelError() } }
        let manager = try makeManager(cacheRoot: cacheRoot, server: server)
        let systemDirectory = manager.systemDirectory
        let installed = try installValid(SyntheticBIOS.catalog[.usa], in: systemDirectory)
        let stamp = try XCTUnwrap(modificationDate(installed))

        do {
            _ = try await manager.prepare(for: rom(regions: ["World"]))
            XCTFail("expected the sentinel transfer failure")
        } catch is SentinelError {}

        XCTAssertEqual(bytes(installed), SyntheticBIOS.usa)
        XCTAssertEqual(modificationDate(installed), stamp)
        XCTAssertEqual(bytes(systemDirectory.appendingPathComponent("scph5500.bin")),
                       SyntheticBIOS.japan)
        XCTAssertEqual(names(in: systemDirectory), ["scph5500.bin", "scph5501.bin"])
    }

    func testBytesThatFailVerificationAreNeverInstalledAndCostNothingElse() async throws {
        let cacheRoot = try tempDirectory()
        let server = liveShapedServer(SyntheticBIOS.catalog)
        server.corruptPayload(id: 103)
        let manager = try makeManager(cacheRoot: cacheRoot, server: server)
        let systemDirectory = manager.systemDirectory
        let installed = try installValid(SyntheticBIOS.catalog[.usa], in: systemDirectory)

        do {
            _ = try await manager.prepare(for: rom(regions: ["World"]))
            XCTFail("expected a digest mismatch")
        } catch let error as FileIntegrityError {
            guard case .digestMismatch = error else {
                return XCTFail("unexpected integrity failure: \(error)")
            }
        }
        // Whatever the server published, the checksum the transfer was told to
        // enforce is the standard image's.
        XCTAssertEqual(server.expectation(forID: 103)?.md5, SyntheticBIOS.catalog.europe.md5)

        XCTAssertEqual(bytes(installed), SyntheticBIOS.usa)
        // No European file, and no part file pretending to be one.
        XCTAssertEqual(names(in: systemDirectory), ["scph5500.bin", "scph5501.bin"])
    }

    func testAnUnwritableBIOSPathFailsWithoutDisturbingTheOtherImages() async throws {
        let cacheRoot = try tempDirectory()
        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: cacheRoot, server: server)
        let systemDirectory = manager.systemDirectory
        let installed = try installValid(SyntheticBIOS.catalog[.japan], in: systemDirectory)
        // Something that is not a file, sitting where the American image goes.
        let blocked = systemDirectory.appendingPathComponent("scph5501.bin", isDirectory: true)
        try FileManager.default.createDirectory(at: blocked, withIntermediateDirectories: true)

        do {
            _ = try await manager.prepare(for: rom(regions: ["USA"]))
            XCTFail("expected an install failure")
        } catch let error as PS1FirmwareError {
            guard case let .installFailed(fileName, _) = error else {
                return XCTFail("unexpected failure: \(error)")
            }
            XCTAssertEqual(fileName, "scph5501.bin")
        }

        XCTAssertEqual(bytes(installed), SyntheticBIOS.japan)
        XCTAssertTrue(FileManager.default.fileExists(atPath: blocked.path))
    }

    func testACancelledPreparationLeavesInstalledBIOSFilesIntact() async throws {
        let cacheRoot = try tempDirectory()
        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: cacheRoot, server: server)
        let systemDirectory = manager.systemDirectory
        let installed = try installValid(SyntheticBIOS.catalog[.usa], in: systemDirectory)
        let stamp = try XCTUnwrap(modificationDate(installed))

        let subject = rom(regions: ["World"])
        let task = Task { try await manager.prepare(for: subject) }
        task.cancel()
        do {
            _ = try await task.value
            // A cancellation that lands after the work finished is not a failure;
            // what matters is that the already-valid image is still there.
        } catch is CancellationError {
        } catch let error as PS1FirmwareError {
            XCTFail("unexpected failure: \(error)")
        }

        XCTAssertEqual(bytes(installed), SyntheticBIOS.usa)
        XCTAssertEqual(modificationDate(installed), stamp)
    }

    // MARK: - Errors a player reads

    func testAMissingBIOSErrorNamesTheExactFileAndOffersRetry() {
        let missing = PS1FirmwareError.firmwareNotOnServer(fileName: "scph5501.bin")
        XCTAssertEqual(missing.fileName, "scph5501.bin")
        XCTAssertTrue(missing.errorDescription?.contains("scph5501.bin") ?? false,
                      "\(missing.errorDescription ?? "nil")")
        XCTAssertTrue(missing.recoverySuggestion?.contains("scph5501.bin") ?? false,
                      "\(missing.recoverySuggestion ?? "nil")")
        XCTAssertTrue(missing.recoverySuggestion?.lowercased().contains("try again") ?? false,
                      "\(missing.recoverySuggestion ?? "nil")")

        for rejection: PS1FirmwareError.Rejection in [
            .missingFromStorage, .unverified, .wrongSize(byteCount: 1, expected: 524_288),
            .declaredChecksumMismatch(declared: String(repeating: "0", count: 32)),
        ] {
            let error = PS1FirmwareError.firmwareUnusable(fileName: "scph5502.bin",
                                                          rejection: rejection)
            XCTAssertEqual(error.fileName, "scph5502.bin")
            XCTAssertTrue(error.errorDescription?.contains("scph5502.bin") ?? false,
                          "\(rejection)")
            XCTAssertTrue(error.recoverySuggestion?.contains("scph5502.bin") ?? false,
                          "\(rejection)")
            XCTAssertTrue(error.recoverySuggestion?.lowercased().contains("try again") ?? false,
                          "\(rejection)")
        }

        let install = PS1FirmwareError.installFailed(fileName: "scph5500.bin", code: 21)
        XCTAssertTrue(install.errorDescription?.contains("scph5500.bin") ?? false)
        XCTAssertTrue(install.recoverySuggestion?.lowercased().contains("try again") ?? false)
    }

    // MARK: - Progress

    func testDownloadProgressComposesWithPackageProgress() async throws {
        let cacheRoot = try tempDirectory()
        let server = liveShapedServer(SyntheticBIOS.catalog)
        let manager = try makeManager(cacheRoot: cacheRoot, server: server)
        let recorder = ProgressRecorder()

        _ = try await manager.prepare(for: rom(regions: ["World"]),
                                      progress: { recorder.record($0) })

        let events = recorder.events
        // The same `PS1PreparationProgress` the package store reports, so one
        // screen can show BIOS retrieval and package assembly as one operation.
        let validating: [String] = events.compactMap {
            if case let .validating(label) = $0 { return label } else { return nil }
        }
        XCTAssertEqual(validating, ["scph5500.bin", "scph5501.bin", "scph5502.bin"])

        var labels: [String] = []
        var completedValues: [Int64] = []
        var totals: [Int64] = []
        for event in events {
            guard case let .downloading(label, completed, total) = event else { continue }
            labels.append(label)
            completedValues.append(completed)
            totals.append(total)
        }
        let total = SyntheticBIOS.byteCount * 3
        XCTAssertFalse(completedValues.isEmpty)
        XCTAssertEqual(Set(totals), [total])
        XCTAssertTrue(completedValues.allSatisfy { $0 >= 0 && $0 <= total })
        XCTAssertEqual(completedValues, completedValues.sorted(),
                       "cumulative progress must never go backwards")
        XCTAssertEqual(completedValues.last, total)
        XCTAssertEqual(Set(labels), ["scph5500.bin", "scph5501.bin", "scph5502.bin"])
    }

    func testAFullyCachedPreparationReportsValidationAndNoDownloads() async throws {
        let cacheRoot = try tempDirectory()
        let server = FakeFirmwareServer()
        let manager = try makeManager(cacheRoot: cacheRoot, server: server)
        let systemDirectory = manager.systemDirectory
        try installValid(SyntheticBIOS.catalog[.usa], in: systemDirectory)
        let recorder = ProgressRecorder()

        _ = try await manager.prepare(for: rom(regions: ["USA"]),
                                      progress: { recorder.record($0) })

        XCTAssertTrue(recorder.events.allSatisfy {
            if case .validating = $0 { return true } else { return false }
        })
        XCTAssertEqual(server.listCalls, [])
    }

    // MARK: - Helpers

    private func assertPrepareFails(_ manager: PS1FirmwareManager,
                                    regions: [String],
                                    with expected: PS1FirmwareError,
                                    file: StaticString = #filePath,
                                    line: UInt = #line) async {
        do {
            _ = try await manager.prepare(for: rom(regions: regions))
            XCTFail("expected \(expected)", file: file, line: line)
        } catch let error as PS1FirmwareError {
            XCTAssertEqual(error, expected, file: file, line: line)
        } catch {
            XCTFail("unexpected error \(error)", file: file, line: line)
        }
    }
}

/// Collects progress from whatever thread reports it.
private final class ProgressRecorder: @unchecked Sendable {
    private let lock = NSLock()
    private var storage: [PS1PreparationProgress] = []

    func record(_ event: PS1PreparationProgress) {
        lock.lock(); storage.append(event); lock.unlock()
    }

    var events: [PS1PreparationProgress] {
        lock.lock(); defer { lock.unlock() }; return storage
    }
}
