#!/usr/bin/env bash
# Writes App/LocalConfig.generated.swift, which lets a development build
# configure itself instead of making you type a URL and an API token on a
# television with a Siri Remote.
#
# This script is tracked and contains no private values. It reads them from two
# untracked files, and writes empty defaults when they are absent — so a fresh
# clone runs this successfully and simply gets the on-screen setup flow.
#
#   Config/local.env  ROMM_BASE_URL       (see Config/local.env.example)
#   .romm.token       the API token, alone on the first line
#
# Baking credentials into the build is a deliberate shortcut for development,
# not the intended end state. The output file is gitignored; keep it that way.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
env_file="$repo_root/Config/local.env"
token_file="$repo_root/.romm.token"
out_file="$repo_root/App/LocalConfig.generated.swift"

base_url=""
token=""

if [[ -f "$env_file" ]]; then
    # Read only the key we want rather than sourcing the file, so a stray
    # command in local.env cannot execute here.
    base_url="$(sed -n 's/^[[:space:]]*ROMM_BASE_URL[[:space:]]*=[[:space:]]*//p' "$env_file" | head -n1)"
    base_url="${base_url%\"}"
    base_url="${base_url#\"}"
    base_url="${base_url%/}"
fi

if [[ -f "$token_file" ]]; then
    token="$(head -n1 "$token_file" | tr -d '[:space:]')"
fi

# Swift string literals: backslashes and quotes must not break out.
escape() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'; }

cat > "$out_file" <<EOF
// Generated by scripts/gen-local-config.sh — do not edit, do not commit.
// Empty values mean "no baked configuration"; the app falls back to on-screen setup.
enum LocalConfig {
    static let defaultBaseURL = "$(escape "$base_url")"
    static let defaultToken = "$(escape "$token")"
}
EOF

if [[ -n "$base_url" && -n "$token" ]]; then
    # Never echo the token or the URL — this runs in shared terminals and logs.
    echo "gen-local-config: wrote baked configuration (server + token present)"
elif [[ -n "$base_url" || -n "$token" ]]; then
    echo "gen-local-config: WARNING — only one of server/token is set; the app will show setup"
else
    echo "gen-local-config: no local configuration found; the app will show setup"
fi
